### ISSUE TITLE
Unclear description for treeStructure in create_cancer_vcfs.py

### ISSUE THREAD

**Issue by mmaitenat** [cbg-ethz/WES_Cancer_Sim#1]
I am trying to mutate a reference genome using your create_cancer_vcfs.py script. However, it's not clear to me the format in which the tree structure should be provided in the config.tsv file. My concrete question is how we can input trees that are not perfect binary trees. An example of such tree would be the following:
(A,B,(C,D)E)R;

Many thanks!

**Comment by arhofman** [comment]
Hi, sorry for the unclear description. This was the config file that we used:
# four levels
>treeLevelRange
0.9 0.5 0.25 0
>treeStructure
1
1 1
1 1 1 1
1 1 1 1 1 1 1 1
>cygocityT
0.5 0.25 0
>cygocityN
0.5 0.25 0

We only used the script 'create_cancer_vcfs.py' with binary trees, and therefore did not add the option of non-binary trees. I hope this helps. 
Bests

**Comment by arhofman** [comment]
`# four levels
>treeLevelRange
0.9 0.5 0.25 0
>treeStructure
1
1 1
1 1 1 1
1 1 1 1 1 1 1 1
>cygocityT
0.5 0.25 0
>cygocityN
0.5 0.25 0
`

**Comment by arhofman** [comment]
Hi, sorry for the unclear description. Here is the config file that we used:

![snapshot_configtsv_sim_cancer_for_create_cancer_vcfpy](https://user-images.githubusercontent.com/20342587/44682068-ab1a6f80-aa42-11e8-8e8f-d3d97c82d6e5.PNG)

We only used the script 'create_cancer_vcfs.py' with binary trees and therefore did not add the option of having non-binary trees. I hope the config file is anyways helpful for you.
Bests

**Comment by mmaitenat** [comment]
Hi!
Many thanks for your response! 
I'm afraid I am still not sure about which trees are allowed. In the sample config file, all nodes have two children. But can I input a binary tree that has a node with [no children](https://en.wikipedia.org/wiki/Binary_tree#/media/File:Full_binary.svg), or with just [one child](https://en.wikipedia.org/wiki/Binary_tree#/media/File:Binary_tree.svg)? 

Thank you!

**Comment by arhofman** [comment]
Hi, we did not put a focus on different tree topologies and therefore did not include the flexibility of allowing various numbers of children. We'd suggest that you use a different method for your purpose that is more flexible such as 'TreeToReads' (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5359950/), or 'SIApopr' (https://www.ncbi.nlm.nih.gov/pubmed/28334409), or 'POMEGRANATE' (https://github.com/viq854/pomegranate). We hope this is helpful. 
Best wishes

**Comment by mmaitenat** [comment]
Many thanks!!
